// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvjosidukxihrzsykwfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2am9zaWR1a3hpaHJ6c3lrd2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMDI1NjIsImV4cCI6MjA4NTg3ODU2Mn0.eXe05kzrW6Y_NNV--ucalpfgMCKWVK3ETdvtKGQVpOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});